RemoteExams: Remote exams
NoSocialMediaLinks: There are no links to social networks
SocialMedia: Social media
Contacts: Contacts
PersonalData: Personal data
Phone: Phone
Filter: Filter
Result: Result
SortBy: Sort by
ExamsPassed: Passed
ExamsFailed: Failed
MainMenu: Main menu
Cancelled: Cancelled
StateMachineDiagram: State machine diagram
Unit: Unit
Hours: Hours
ExamWasCancelled: The exam was cancelled
ExamCompleted: Exam completed
InvalidExam: Invalid exam
ExamTimeHasExpired: The exam time has expired
TimeIsUp: Time is up
AllottedExamTimeHasExpired: The time allotted for the exam has expired
Timeout: Timeout
Completed: Completed
Ongoing: Ongoing
Started: Started
UseCaseDiagram: Use Case Diagram
NoExamsWereFoundForSearchTerms: No exams were found that matched all of your search terms
ExamSuccessfullyCancelled: The exam was successfully cancelled
LoginRequired: Login required
YouNeedToLoginForExam: To sign up for an exam you need to log in
TestYourSkillsWith: Test your skills with
Welcome: Welcome
AvailableTests: Available tests
PassedExams: Passed exams
TestYourSkills: Test your skills
RetakeThisExam: Retake this exam
NoQuestionsForTheTest: There are no questions for the test
SelectATestForTheExam: Select a test for the exam
LoginToSeeYourExamsPlease: Please log in to see your exams
LoginPlease: Please log in to access this page
AnotherAccountAccessProhibited: Access to another user's account is prohibited
PleaseLogInToIdentifyYourselfAsExamCandidate: Please log in to identify yourself as an exam candidate
InvalidUrlOrRemoved: Invalid URL or resource removed
Or: or
BackToHomepage: Go back to homepage
InvalidArguments: Invalid arguments
PermissionDenied: Permission denied
PageNotFound: Page not found
ConfirmPlease: Please confirm
UploadPhoto: Upload photo
PasswordChanged: Password changed
PasswordDoesNotMatch: The password does not match
RepeatPassword: Repeat password
SuperuserCannotBeDeleted: Superuser cannot be deleted
PasswordChange: Password change
ChangePassword: Change password
RecordAdded: Record added
AlreadyExists: Already exists
Attribution: Attribution
No: No
Yes: Yes
Dele: Delete
Email: Email
Users: Users
TakePhoto: Take a photo
DemoUserAccounts: Demo user accounts
User: User
Superuser: Superuser
Administrator: Administrator
Username: Username
Password: Password
AccessDeniedAdminsOnly: Only administrators have access to this page. Please log in with an administrator account
SignInToAccessPlease: Please sign in to access this page
Home: Home
Logo: Logo
TotalCandidates: Total candidates
NoTestsYet: There are no tests yet
NoCandidatesYet: There are no candidates yet
TimeRemaining: Time remaining
PassedFailedExamNumber: Number of passed and failed exams
ExamSuccessRate: Exam success rate
PassRate: Pass rate
Test: Test
Tests: Tests
Total: Total
NumberOfExaminees: Number of examinees
SuccessRate: Success rate
Rating: Rating
Select: Select
ExamInfo: Exam info
PassExamInvite: Pass an exam to assess and validate skills
NoExamsYet: There are no exams yet
NoSkillsYet: There are no skills yet
DiagramERD: Entity Relationship Diagram
ExamDuration: Exam duration
ExamTime: Exam time
NumberOfQuestions: Number of questions
OfTotal: of
Overview: Overview
ExamList: Exam list
NoPublishedExamsYet: There are no published exams yet
Unpublish: Unpublish
Publish: Publish
Unpublished: Unpublished
Published: Published
ExamState: State
TopExams: Top exams
TopSkilled: Top skilled
Data: Data
Resources: Resources
SourceCode: Source code
RecordEdited: Record edited
RecordDeleted: Record deleted
NewRecordAdded: New record added
MultiLineQuestion: Multiple line question
SingleLineQuestion: Single line question
MultiLine: Multiple line
SingleLine: Single line
EnrollForExam: Enroll for exam
ResponseOptions: Response options
ExamQuestions: Exam questions
NoExamsFoundFor skey@Text: No exams found for "#{skey}"
NoDataFound: No data found
SingleResponse: Single response
MultiResponse: Multiple response
Instruction: Instruction
Submitted: Submitted
TimeCompleted: Completed
Analytics: Analytics
MaxScore: Max score
PassScore: Pass score
Score: Score
Fail: Fail
Pass: Pass
Status: Status
ExamResults: Exam results
Print: Print
Complete: Complete
Stop: Stop
StopThisExam: Stop this exam?
TerminateThisExam: Terminate this exam?
DifficultyHigh: High
DifficultyMedium: Medium
DifficultyLow: Low
Difficulty: Difficulty
Points: Points
Minutes: Minutes
Popularity: Popularity
LoginPrompt: Please login to find your exams.
NoExams: You haven't taken any exams yet
AssessedSkills: Assessed skills
TakeThisExam: Take this exam
DataAndAnalytics: Data & Analytics
Administration: Administration
Configuration: Configuration
Settings: Settings
ChooseExam: Choose exam
PassMark: Pass mark
TimeEnd: Time end
TimeStart: Time start
Summary: Summary
Finish: Finish
Authenticate: Authenticate
Authentication: Authentication
SignIn: Sign in
RegisterAsCandidate: Register as candidate
RegisterNewCandidate: Register new candidate
Logout: Logout
Login: Login
MyExam: My exam
MyExams: My exams
TakeNewExam: Take new exam
TakeExam: Take an exam
Next: Next
Previous: Previous
Attempt: Attempt
Duration: Duration
StartExam: Start exam
Date: Date
Day: Day
Enrollment: Enrollment
Enroll: Enroll
Age: Age
FullName: Full name
Actions: Actions
Photo: Photo
Birthday: Birthday
AdditionalName: Middle name
GivenName: First name
FamilyName: Last name
Type: Type
Distractor: Distractor
Key: Key
AnswerPoints: Points
CorrectAnswer: Correct answer
AnswerOption: Answer option
AnswerOptions: Answer options
Answer: Answer
Answers: Answers
Option: Option
Options: Options
Text: Text
Ordinal: Ordinal
Question: Question
Questions: Questions
Back: Back
BasicEntities: Basic Entities
DuplicateValue: Duplicate value
Id: Id
Details: Details
DeleteAreYouSure: The data will be deleted. Are you sure?
AreYouSureDelete: Are you sure you want to delete?
PleaseConfirm: Please confirm
ConfirmationRequired: Confirmation required
InvalidFormData: Invalid form data
InvalidData: Invalid data
Close: Close
Delete: Delete
Edit: Edit
Descr: Description
Name: Name
Code: Code
Cancel: Cancel
Save: Save
Attributes: Attributes
Search: Search
Add: Add
HomePage: Home page
Candidate: Candidate
Candidates: Candidates
Exam: Exam
Exams: Exams
Skill: Skill
Skills: Skills
AppName: SkillExam
MetaKeywords: Multiple-Choice, Questions, MCQ, Skills, Assessment, Candidate
MetaDescription: Assessment of skills, Multiple-Choice Questions

Docs: Docs
Doc001: The application "SkillExam" provides an easy way to assess a candidate's skills with Multiple-Choice Questions tests.

Doc002 hrefSkills@Text: The skills to be assessed must be defined in the <a href=#{hrefSkills}>"Skills"</a> section in the "Data" group, accessible from the main menu. Skills can be thought of as elements for grouping questions for a test.

Doc003 hrefTests@Text: Tests to assess a candidate's skills are defined in the <a href=#{hrefTests}>"Tests"</a> section in the group "Data" of the main menu. A Test consists of questions.

Doc004 hrefCandidates@Text: Candidates for the exam are recorded in the <a href=#{hrefCandidates}>"Candidates"</a> section in the "Data" group of the main menu.

Doc005 hrefExams@Text: A candidate can choose an exam from the <a href=#{hrefExams}>"Exams"</a> list, register for the exam and start the exam.

Doc006 hrefMyExams@Text: Upon completion of the exam, a summary is provided and the candidate can see the results of the exam in the <a href=#{hrefMyExams}>"My exams"</a> section.

Doc007 hrefSkills@Text: A Skill is recorded in the <a href=#{hrefSkills}>"Skills"</a> section with a unique code, name and description.

Doc008 hrefCandidates@Text: A Candidate is registered in the <a href=#{hrefCandidates}>"Candidates"</a> section by providing its full name and, optionally, a photo and birthday.

Doc009 hrefTests@Text: A Test is defined in the <a href=#{hrefTests}>"Tests"</a> section by providing a unique code, a name, optionally a description, its duration in minutes, and a passing score.

Doc010: It is recommended that a Test remain in the "Unpublished" state until it is ready for publication by defining and configuring all of its subcomponents: Questions and Answer Options.

Doc011: A Test is composed from multiple Questions.

Doc012: A single Test may cover several Skills specific to each Question.

Doc013: A Question (Stem) for a particular test is defined by providing an ordinal number, the question itself as text, the question type, the instruction, and the Skill it addresses.

Doc014: If necessary, the text of the Question can be formatted with <code>HTML/CSS</code>.

Doc015: The type of a Question may be one of "Single response" or "Multiple response".

Doc016: For "Single response" questions, the candidate is asked to select only one answer from the options provided.

Doc017: For "Multiple response" questions, the candidate is asked to select all of the answers that are correct from the options provided.

Doc018: For each Question, several answer Options are provided.

Doc019: A response Option is entered by providing an index (ordinal), a response as text, whether the response is a "key" or a "distractor", and a value for the score.

Doc020: If necessary, the text of the response Option can be formatted with <code>HTML/CSS</code>.

Doc021: After all Options have been provided for all Questions of a Test, the Test can be published.

Doc022 hrefExams@Text: A Candidate can now enroll for an exam by choosing a test from the list <a href=#{hrefExams}>"Exams"</a>.

Doc023: An Exam represents a particular instance of a Test for a Candidate.

Doc024: It describes when the Exam started and ended for the Candidate. It also tracks the number of attempts a Candidate tries to pass the same Test.

Doc025: After enrollment the candidate starts the Exam and its Answers are recorded.

Doc026: An Answer represents the Option for a given Question that a Candidate considers to be the correct one.

Doc027: Once the exam time has expired, the system notifies the candidate and forces him to finish the exam