TotalPoints: Total des points
ExamCode: Code d'examen
ExamName: Nom de l'examen
ThisIsTheStartPageOfTheExam: Ceci est la page de démarrage de l'examen
NoExamFoundAtThisLink: Aucun examen trouvé sur ce lien
LinksForExamsGenerated: Des liens pour les examens ont été générés
CopyLink: Copier le lien
NoRegisteredCandidatesHaveBeenSelected: Aucun candidat inscrit n'a été sélectionné
Create: Créer
YouAreAboutToCreateExamForUnregisteredCandidates: Vous êtes sur le point de créer un examen pour les candidats non inscrits
YouAreAboutToCreateExamForCandidate: Vous êtes sur le point de créer un examen pour un candidat
YouAreAboutToCreateExamForCandidates m: Vous êtes sur le point de créer un examen pour #{show m} candidats
Valid: Valide
Author: Auteur
DateCreated: Date de création
ForPotentialCandidates: Pour les candidats potentiels
ForRegisteredCandidate: Pour un candidat inscrit
RemoteTest: Test à distance
RemoteTests: Tests à distance
ExamLink: Lien vers l'examen
RemoteExam: Examen à distance
RemoteExams: Examens à distance
NoSocialMediaLinks: Il n'y a pas de liens vers les réseaux sociaux
SocialMedia: Réseaux sociaux
Contacts: Contacts
PersonalData: Données personnelles
Phone: Téléphone
Filter: Filtre
Result: Résultat
SortBy: Trier par
ExamsPassed: Réussis
ExamsFailed: Échoués
MainMenu: Menu principal
Cancelled: Annulé
StateMachineDiagram: Diagramme de machine d'état
Unit: Unité 
Hours: Heures
ExamWasCancelled: L'examen a été annulé
ExamCompleted: Examen terminé
InvalidExam: Examen invalide
ExamTimeHasExpired: Le temps d'examen est expiré
TimeIsUp: Le temps s'est écoulé
AllottedExamTimeHasExpired: Le temps alloué à l'examen est expiré
Timeout: Délai expiré
Completed: Terminé
Ongoing: En cours 
Started: Commencé
UseCaseDiagram: Diagramme de cas d'utilisation
NoExamsWereFoundForSearchTerms: Aucun examen correspondant à tous vos termes de recherche n'a été trouvé
ExamSuccessfullyCancelled: L'examen a été annulé avec succès
LoginRequired: Connexion requise
YouNeedToLoginForExam: Pour vous inscrire à un examen, vous devez vous connecter
TestYourSkillsWith: Testez vos compétences avec
Welcome: Bienvenu
AvailableTests: Tests disponibles
PassedExams: Examens réussis
TestYourSkills: Testez vos compétences
RetakeThisExam: Reprendre cet examen
NoQuestionsForTheTest: Il n'y a pas de questions pour le test
SelectATestForTheExam: Sélectionnez un test pour l'examen
LoginToSeeYourExamsPlease: Veuillez vous connecter pour voir vos examens
LoginPlease: Veuillez vous connecter pour accéder à cette page
AnotherAccountAccessProhibited: L'accès au compte d'un autre utilisateur est interdit
PleaseLogInToIdentifyYourselfAsExamCandidate: Veuillez vous connecter pour vous identifier en tant que candidat à l'examen
InvalidUrlOrRemoved: URL non valide ou ressource supprimée
Or: ou
BackToHomepage: Retour à la page d'accueil
InvalidArguments: Arguments invalides
PermissionDenied: Permission refusée
PageNotFound: Page non trouvée
ConfirmPlease: Veuillez confirmer
UploadPhoto: Télécharger une photo
PasswordChanged: Mot de passe changé
PasswordDoesNotMatch: Le mot de passe ne correspond pas
RepeatPassword: Répéter le mot de passe
SuperuserCannotBeDeleted: Le superutilisateur ne peut pas être supprimé
PasswordChange: Changement de mot de passe
ChangePassword: Changer le mot de passe
RecordAdded: Enregistrement ajouté
AlreadyExists: Existe déjà
Attribution: Attribution
No: Non
Yes: Oui
Dele: Supprimer
Email: E-mail
Users: Utilisateurs
TakePhoto: Prendre une photo
DemoUserAccounts: Comptes d'utilisateurs démo
User: Utilisateur
Superuser: Superutilisateur
Administrator: Administrateur
Username: Nom d'utilisateur
Password: Mot de passe
AccessDeniedAdminsOnly: Seuls les administrateurs ont accès à cette page. Veuillez vous connecter avec un compte administrateur
SignInToAccessPlease: Veuillez vous connecter pour accéder à cette page
Home: Accueil
Logo: Logo
TotalCandidates: Candidats totaux
NoTestsYet: Il n'y a pas encore de tests
NoCandidatesYet: Il n'y a pas encore de candidats
TimeRemaining: Temps restant
PassedFailedExamNumber: Le nombre d'examens réussis et échoués
ExamSuccessRate: Taux de réussite aux examens
PassRate: Taux de réussite
Test: Test
Tests: Tests
Total: Total
NumberOfExaminees: Nombre de candidats
SuccessRate: Taux de réussite
Rating: Classement
Select: Sélectionner
ExamInfo: Informations sur l'examen
PassExamInvite: Passer un examen pour évaluer et valider les compétences
NoExamsYet: Il n'y a pas encore d'examens
NoSkillsYet: Il n'y a pas encore de compétences
DiagramERD: Diagramme entité-relation
ExamDuration: Durée de l'examen
ExamTime: La durée de l'examen
NumberOfQuestions: Nombre de questions
OfTotal: sur
Overview: Aperçu
ExamList: Liste des examens
NoPublishedExamsYet: Il n'y a pas encore d'examens publiés
Unpublish: Dépublier
Publish: Publier
Unpublished: Non publiée
Published: Publié
ExamState: État
TopExams: Examens populaires
TopSkilled: Top qualifié
Data: Données
Resources: Ressources
SourceCode: Code source
RecordEdited: Enregistrement modifié
RecordDeleted: Enregistrement supprimé
NewRecordAdded: Nouvel enregistrement ajouté
MultiLineQuestion: Question sur plusieurs lignes
SingleLineQuestion: Question sur une seule ligne
MultiLine: Plusieurs lignes
SingleLine: Une seule ligne
EnrollForExam: S'inscrire à l'examen
ResponseOptions: Possibilités de réponse
ExamQuestions: Questions d'examen
NoExamsFoundFor skey: Aucun examen trouvé pour "#{skey}"
NoDataFound: Aucune donnée disponible
SingleResponse: Réponse unique
MultiResponse: Réponse multiple
Instruction: Instruction
Submitted: Soumis
TimeCompleted: Terminé
Analytics: Analytique
MaxScore: Note maximale
PassScore: Note de réussite
Score: Note d'examen
Fail: Échec
Pass: Réussite
Status: Statut
ExamResults: Résultats d'examen
Print: Imprimer
Complete: Terminer
Stop: Arrêter
StopThisExam: Arrêter cet examen?
TerminateThisExam: Terminer cet examen?
DifficultyHigh: Élevée
DifficultyMedium: Moyenne
DifficultyLow: Faible
Difficulty: Difficulté
Points: Points
Minutes: Minutes
Popularity: Popularité
LoginPrompt: Veuillez vous connecter pour trouver vos examens.
NoExams: Vous n'avez pas encore passé d'examens
AssessedSkills: Compétences évaluées
TakeThisExam: Passer cet examen
DataAndAnalytics: Données et analyses
Administration: Administration
Configuration: Configuration
Settings: Paramètres
ChooseExam: Choisir examen
PassMark: Note de passage
TimeEnd: Heure de fin
TimeStart: Heure de début
Summary: Résumé
Finish: Finir
Authenticate: Authentifiez-vous
Authentication: Authentification
SignIn: Connectez-vous
RegisterAsCandidate: S'inscrire comme candidat
RegisterNewCandidate: Inscrire un nouveau candidat
Logout: Se déconnecter
Login: Se connecter
MyExam: Mon examen
MyExams: Mes examens
TakeNewExam: Passer un nouvel examen
TakeExam: Passer un examen
Next: Suivant
Previous: Précédent
Attempt: Tentative
Duration: Durée
StartExam: Commencer l'examen
Date: Date
Day: Jour
Enrollment: Enrôlement
Enroll: S'inscrire
Age: Âge
FullName: Nom complet
Actions: Actions
Photo: Photo
Birthday: Date d'anniversaire
AdditionalName: Deuxième nom
GivenName: Prénom
FamilyName: Nom de famille
Type: Type
Distractor: Distracteur
Key: Clé
AnswerPoints: Points
CorrectAnswer: Réponse correcte
AnswerOption: Option de réponse
AnswerOptions: Possibilités de réponse
Answer: Réponse
Answers: Réponses
Option: Option
Options: Options
Text: Texte
Ordinal: Ordinal
Question: Question
Questions: Questions
Back: Retour
BasicEntities: Entités de base
DuplicateValue: Valeur en double
Id: Id
Details: Détails
DeleteAreYouSure: Les données seront supprimées. Es-tu sûr?
AreYouSureDelete: Etes-vous sûr que vous voulez supprimer?
PleaseConfirm: Veuillez confirmer
ConfirmationRequired: Confirmation requise
InvalidFormData: Les données sont invalides
InvalidData: Données invalides
Close: Fermer
Delete: Supprimer
Edit: Modifier
Descr: Description
Name: Nom
Code: Code
Cancel: Annuler
Save: Enregistrer
Attributes: Attributs
Search: Rechercher
Add: Ajouter
HomePage: Page d'accueil
Candidate: Candidat
Candidates: Candidats
Exam: Examen
Exams: Examens
Skill: Compétence
Skills: Compétences
AppName: SkillExam
MetaKeywords: QCM, Questions, Compétences, Évaluation, Candidat
MetaDescription: Évaluation des compétences, QCM, Questions à choix multiples

Docs: Documentation 
Doc001: L'application «SkillExam» offre un moyen simple d'évaluer les compétences d'un candidat au moyen de questions à choix multiples.

Doc002 hrefSkills: Les compétences à évaluer doivent être définies dans la rubrique <a href=#{hrefSkills}>«Compétences»</a> du groupe «Données», accessible depuis le menu principal. Les compétences peuvent être considérées comme des éléments permettant de regrouper les questions d'un test.

Doc003 hrefTests: Les tests permettant d'évaluer les compétences d'un candidat sont définis dans la section <a href=#{hrefTests}>«Tests»</a> du groupe «Données» du menu principal. Un test est composé de questions.

Doc004 hrefCandidates: Les candidats à l'examen sont enregistrés dans la section <a href=#{hrefCandidates}>«Candidats»</a> du groupe «Données» du menu principal.

Doc005 hrefExams: Un candidat peut choisir un examen dans la liste des <a href=#{hrefExams}>«Examens»</a>, s'inscrire à l'examen et commencer l'examen.

Doc006 hrefMyExams: À la fin de l'examen, un résumé est fourni et le candidat peut voir les résultats de l'examen dans la section <a href=#{hrefMyExams}>«Mes examens»</a>.

Doc007 hrefSkills: Une Compétence est enregistrée dans la section <a href=#{hrefSkills}>«Compétences»</a> avec un code unique, un nom et une description.

Doc008 hrefCandidates: Un Candidat est enregistré dans la rubrique <a href=#{hrefCandidates}>«Candidats»</a> en fournissant son nom complet et éventuellement une photo et sa date de naissance.

Doc009 hrefTests: Un Test est défini dans la rubrique <a href=#{hrefTests}>«Tests»</a> en fournissant un code unique, un nom, éventuellement une description, sa durée en minutes, sa note de passage.

Doc010: Il est recommandé qu'un test reste à l'état «Non publié» jusqu'à ce qu'il soit prêt à être publié en définissant et en configurant tous ses sous-composants: questions et options de réponse.

Doc011: Un test est composé de plusieurs questions.

Doc012: Un même test peut couvrir plusieurs compétences spécifiques à chaque question.

Doc013: Une question pour un test particulier est définie en fournissant un nombre ordinal, la question elle-même sous forme de texte, le type de question, l'instruction et la compétence qu'elle aborde.

Doc014: Si nécessaire, le texte de la question peut être formaté avec <code>HTML/CSS</code>.

Doc015: Le type d'une Question peut être «Réponse unique» ou «Réponse multiple».

Doc016: Pour les questions à «Réponse unique», le candidat est invité à sélectionner une seule réponse parmi les options proposées.

Doc017: Pour les questions à «Réponse multiple», le candidat est invité à sélectionner toutes les réponses correctes parmi les options proposées.

Doc018: Pour chaque question, plusieurs options de réponse sont proposées.

Doc019: Une option de réponse est entrée en fournissant un index (numéro de séquence), une réponse textuelle, si la réponse est une «clé» ou une «distraction», et une valeur de score.

Doc020: Si nécessaire, le texte de l'option de réponse peut être formaté avec <code>HTML/CSS</code>.

Doc021: Une fois que toutes les options de réponse ont été fournies pour toutes les questions d'un test, le test peut être publié.

Doc022 hrefExams: Un candidat peut désormais s'inscrire à un examen en choisissant un test dans la liste <a href=#{hrefExams}>«Examens»</a>.

Doc023: Un Examen représente une instance particulière d'un test pour un candidat.

Doc024: Il décrit quand l'examen a commencé et s'est terminé pour un candidat. Il suit également le nombre de tentatives d'un candidat pour réussir le même test.

Doc025: Après l'inscription, le candidat commence l'examen et ses réponses sont enregistrées.

Doc026: Une réponse représente l'option pour une question donnée qu'un candidat considère comme la bonne.

Doc027: Une fois le temps d'examen expiré, le système avertit le candidat et l'oblige à terminer l'examen