Timeout: Timp expirat
Completed: Finalizat
Ongoing: În desfășurare 
Started: Început
UseCaseDiagram: Diagrama cazurilor de utilizare
NoExamsWereFoundForSearchTerms: Nu au fost găsite examene care să corespundă tuturor termenilor dvs. de căutare
ExamSuccessfullyCancelled: Examenul a fost anulat cu succes
LoginRequired: Autentificare necesară
YouNeedToLoginForExam: Pentru a vă înscrie la un examen trebuie să vă autentificați
TestYourSkillsWith: Testează-ți abilitățile cu
Welcome: Bine ați venit
AvailableTests: Teste disponibile
PassedExams: Examenele promovate
TestYourSkills: Testează-ți abilitățile
RetakeThisExam: Reluați acest examen
NoQuestionsForTheTest: Nu există întrebări pentru test
SelectATestForTheExam: Selectați un test pentru examen
LoginToSeeYourExamsPlease: Vă rugăm să vă conectați pentru a vă vedea examenele
LoginPlease: Vă rugăm să vă conectați pentru a accesa această pagină
AnotherAccountAccessProhibited: Accesul la contul altui utilizator este interzis
PleaseLogInToIdentifyYourselfAsExamCandidate: Vă rugăm să vă conectați pentru a vă identifica ca candidat la examen
InvalidUrlOrRemoved: Adresă URL nevalidă sau resursă eliminată
Or: sau
BackToHomepage: Reveniți la pagina de pornire
InvalidArguments: Argumente nevalide
PermissionDenied: Acces refuzat
PageNotFound: Pagina nu a fost găsită
ConfirmPlease: Vă rugăm să confirmați
UploadPhoto: Încărcați o fotografie
PasswordChanged: Parola schimbată
PasswordDoesNotMatch: Parola nu se potrivește
RepeatPassword: Repetați parola
SuperuserCannotBeDeleted: Superutilizatorul nu poate fi șters
PasswordChange: Schimbarea parolei
ChangePassword: Schimbaţi parola
RecordAdded: Înregistrare adăugată
AlreadyExists: Deja există
Attribution: Atribuire
No: Nu
Yes: Da
Dele: Şterge
Email: E-mail
Users: Utilizatori
TakePhoto: Faceți o poză
DemoUserAccounts: Conturi de utilizator Demo
User: Utilizator
Superuser: Superutilizator
Administrator: Administrator
Username: Nume de utilizator
Password: Parolă
AccessDeniedAdminsOnly: Doar administratorii au acces la această pagină. Vă rugăm să vă conectați cu un cont de administrator
SignInToAccessPlease: Vă rugăm să vă conectați pentru a accesa această pagină
Home: Acasă
Logo: Logo
TotalCandidates: Total candidați
NoTestsYet: Nu există încă teste
NoCandidatesYet: Nu există încă candidați
TimeRemaining: Timpul ramas
PassedFailedExamNumber: Numărul de examene promovate și eșuate
ExamSuccessRate: Rata de succes la examen
PassRate: Rata de promovare
Test: Test
Tests: Teste
Total: Total
NumberOfExaminees: Numărul de examinați
SuccessRate: Rata de succes
Rating: Clasificare
Select: Selectați
ExamInfo: Informații despre examen
PassExamInvite: Susține un examen pentru a evalua și valida abilitățile
NoExamsYet: Nu există examene încă
NoSkillsYet: Nu există abilități încă
DiagramERD: Diagrama entitate-relatie
ExamDuration: Durata examenului
ExamTime: Durata examenului
NumberOfQuestions: Numărul de întrebări
OfTotal: din
Overview: Prezentare generală
ExamList: Lista examenelor
NoPublishedExamsYet: Nu există încă examene publicate
Unpublish: Anulează publicarea
Publish: Publicați
Unpublished: Nepublicat
Published: Publicat
ExamState: Starea
TopExams: Examene populare
TopSkilled: Top calificați
Data: Date
Resources: Resurse
SourceCode: Codul sursă
RecordEdited: Înregistrarea a fost editată
RecordDeleted: Înregistrarea a fost ștearsă
NewRecordAdded: A fost adăugată o nouă înregistrare
MultiLineQuestion: Întrebare cu mai multe rânduri
SingleLineQuestion: Întrebare pe un singur rând
MultiLine: Linie multiplă
SingleLine: O singura linie
EnrollForExam: Inscriere la examen
ResponseOptions: Opțiunile de răspuns
ExamQuestions: Întrebări de examen
NoExamsFoundFor skey: Nu s-au găsit examene pentru „#{skey}”
NoDataFound: Nu s-au gasit date
SingleResponse: Răspuns unic
MultiResponse: Răspuns multiplu
Instruction: Instrucțiune
Submitted: Depus
TimeCompleted: Finalizat
Analytics: Analiza
MaxScore: Scorul maxim
PassScore: Scorul de promovare
Score: Scor
Fail: Eșuat
Pass: Succes
Status: Starea
ExamResults: Rezultatele examenului
Print: Printează
Complete: Terminare
Stop: Oprește
StopThisExam: Oprește acest examen?
TerminateThisExam: Întrerupeți acest examen?
DifficultyHigh: Ridicată
DifficultyMedium: Medie
DifficultyLow: Scăzută
Difficulty: Dificultatea
Points: Puncte
Minutes: Minute
Popularity: Popularitate
LoginPrompt: Vă rugăm să vă autentificați pentru a vă găsi examenele.
NoExams: Încă nu ai susținut niciun examen
AssessedSkills: Abilități evaluate
TakeThisExam: Susține acest examen
DataAndAnalytics: Date și analize
Administration: Administrare
Configuration: Configurare
Settings: Setări
ChooseExam: Alege examen
PassMark: Nota de promovare
TimeEnd: Ora încheierii
TimeStart: Ora începerii
Summary: Rezumat
Finish: Finalizare
Authenticate: Autentificați-vă
Authentication: Autentificare
SignIn: Conectare
RegisterAsCandidate: Înscrieți-vă ca candidat
RegisterNewCandidate: Înregistrați un candidat nou
Logout: Deconectare
Login: Autentificare
MyExam: Examenul meu
MyExams: Examenele mele
TakeNewExam: Susține un examen nou
TakeExam: Susține un examen
Next: Următorul
Previous: Anterior
Attempt: Încercare
Duration: Durată
StartExam: Începe examenul
Date: Data
Day: Ziua
Enrollment: Înscriere
Enroll: Înscrie-te
Age: Vârsta
FullName: Numele complet
Actions: Acțiuni
Photo: Foto
Birthday: Ziua de nastere
AdditionalName: Al doilea nume
GivenName: Prenume
FamilyName: Nume
Type: Tip
Distractor: Distragător
Key: Cheie
AnswerPoints: Puncte
CorrectAnswer: Răspuns corect
AnswerOption: Opțiune de răspuns
AnswerOptions: Opțiuni de răspuns
Answer: Răspuns
Answers: Răspunsuri
Option: Opțiune
Options: Opțiuni
Text: Text
Ordinal: Ordinal
Question: Întrebare
Questions: Întrebări
Back: Înapoi
BasicEntities: Entităţile de bază
DuplicateValue: Valoarea duplicată
Id: Id
Details: Detalii
DeleteAreYouSure: Datele vor fi șterse. Esti sigur?
AreYouSureDelete: Ești sigur că vrei să ștergi?
PleaseConfirm: Vă rugăm să confirmați
ConfirmationRequired: Este necesară confirmarea
InvalidFormData: Datele sunt nevalide
InvalidData: Date nevalide
Close: Închide
Delete: Șterge
Edit: Editare
Descr: Descriere
Name: Nume
Code: Cod
Cancel: Anulează
Save: Salvează
Attributes: Atribute
Search: Căutare
Add: Adaugă
HomePage: Pagina principală
Candidate: Candidat
Candidates: Candidați
Exam: Examen
Exams: Examene
Skill: Abilitate
Skills: Abilități
AppName: SkillExam
MetaKeywords: Test grilă, Întrebări, MCQ, Abilități, Evaluare, Candidat
MetaDescription: Evaluarea abilităților, Întrebări cu răspunsuri multiple, Test grilă

Docs: Documentație
Doc001: Aplicația „SkillExam” oferă o modalitate simplă de a evalua abilitățile candidatului prin intermediul întrebărilor cu răspunsuri multiple.

Doc002 hrefSkills: Abilitățile de evaluat trebuie definite în secțiunea <a href=#{hrefSkills}>„Abilități”</a> din grupul „Date”, accesibilă din meniul principal. Abilitățile pot fi considerate ca elemente pentru gruparea întrebărilor pentru un test.

Doc003 hrefTests: Testele de evaluare a aptitudinilor unui candidat sunt definite în secțiunea <a href=#{hrefTests}>„Teste”</a> din grupul „Date” din meniul principal. Un test constă din întrebări.

Doc004 hrefCandidates: Candidații la examen sunt înregistrați în secțiunea <a href=#{hrefCandidates}>„Candidați”</a> din grupul „Date” din meniul principal.

Doc005 hrefExams: Un candidat poate alege un examen din lista de <a href=#{hrefExams}>„Examene”</a>, se poate înscrie la examen și poate începe examenul.

Doc006 hrefMyExams: La finalizarea examenului, este oferit un rezumat, iar candidatul poate vedea rezultatele examenului în secțiunea <a href=#{hrefMyExams}>„Examenele mele”</a>.

Doc007 hrefSkills: O Competenţă este înregistrată în secţiunea <a href=#{hrefSkills}>„Abilități”</a> cu un cod unic, un nume şi o descriere.

Doc008 hrefCandidates: Un Candidat este înregistrat în secțiunea <a href=#{hrefCandidates}>„Candidați”</a> furnizând numele complet și, opțional, o fotografie și ziua de naștere.

Doc009 hrefTests: Un Test este definit în secțiunea <a href=#{hrefTests}>„Teste”</a> prin furnizarea unui cod unic, a unui nume, opțional o descriere, durata acestuia în minute, nota de trecere.

Doc010: Se recomandă ca Testul să rămână în starea „Nepublicat” până când este gata de publicare prin definirea și configurarea tuturor subcomponentelor sale: Întrebări și Opțiuni de răspuns.

Doc011: Un Test este compus din mai multe întrebări.

Doc012: Un singur Test poate acoperi mai multe abilități specifice fiecărei întrebări.

Doc013: O Întrebare pentru un anumit test este definită prin furnizarea unui număr ordinal, întrebarea în sine ca text, tipul de întrebare, instrucțiunea și Competența pe care o abordează.

Doc014: Dacă este necesar, textul Întrebării poate fi formatat cu <code>HTML/CSS</code>.

Doc015: Tipul unei întrebări poate fi unul dintre „Răspuns unic” sau „Răspuns multiplu”.

Doc016: Pentru întrebările „Răspuns unic”, candidatului i se cere să selecteze un singur răspuns dintre opțiunile oferite.

Doc017: Pentru întrebările „Răspuns multiplu”, candidatului i se cere să selecteze toate răspunsurile care sunt corecte dintre opțiunile oferite.

Doc018: Pentru fiecare întrebare, sunt oferite mai multe opțiuni de răspuns.

Doc019: O opțiune de răspuns este introdusă prin furnizarea unui index (ordinal), a unui răspuns ca text, dacă răspunsul este o „cheie” sau un „distractor” și o valoare pentru scor.

Doc020: Dacă este necesar, textul opțiunii de răspuns poate fi formatat cu <code>HTML/CSS</code>.

Doc021: După ce toate Opțiunile de răspuns au fost furnizate pentru toate întrebările unui test, testul poate fi publicat.

Doc022 hrefExams: Un Candidat se poate înscrie acum la un examen alegând un test din lista <a href=#{hrefExams}>„Examene”</a>.

Doc023: Un Examen reprezintă o anumită instanță a unui test pentru un candidat.

Doc024: Descrie când a început și s-a încheiat examenul pentru un candidat. De asemenea, urmărește numărul de încercări pe care un candidat încearcă să promoveze același test.

Doc025: După înregistrare, candidatul începe examenul și răspunsurile acestuia sunt înregistrate.

Doc026: Un răspuns reprezintă opțiunea pentru o anumită întrebare pe care un candidat o consideră a fi cea corectă.